; Stable aliases for the supported Durotar route. Original indexes remain intact.
DEF PEON_MOB_TIGER EQU MEOWTH
DEF PEON_MOB_RAPTOR EQU TOTODILE
DEF PEON_MOB_CRAWLER EQU KRABBY
DEF PEON_MOB_HARPY EQU SPEAROW
DEF PEON_MOB_FELSTALKER EQU EKANS
DEF PEON_MOB_CULTIST EQU GRIMER
DEF PEON_MOB_YARROG EQU MACHOKE
DEF PEON_MOB_SARKOTH EQU KINGLER
DEF PEON_SPRITE_TIGER EQU SPRITE_BUG_CATCHER
DEF PEON_SPRITE_RAPTOR EQU SPRITE_TWIN
DEF PEON_SPRITE_CRAWLER EQU SPRITE_LASS
DEF PEON_SPRITE_HARPY EQU SPRITE_TEACHER
DEF PEON_SPRITE_FELSTALKER EQU SPRITE_BEAUTY
DEF PEON_SPRITE_CULTIST EQU SPRITE_SUPER_NERD
DEF PEON_SPRITE_YARROG EQU SPRITE_ROCKER
DEF PEON_SPRITE_SARKOTH EQU SPRITE_JANINE
DEF PEON_SPRITE_INNKEEPER EQU SPRITE_BLAINE

; Append-only aliases: existing item numbers and battery layout stay stable.
DEF PEON_SARKOTH_CLAW EQU ITEM_91
DEF PEON_BLADE_MEDALLION EQU ITEM_93
DEF PEON_SPIRIT_MACE EQU ITEM_8E
DEF PEON_EARTH_TOTEM EQU ITEM_94

; Three reserved variable sprites keep their VRAM allocation stable while
; each independent quest marker changes its appearance.
DEF SPRITE_PEON_QUEST_1 EQU $fd
DEF SPRITE_PEON_QUEST_2 EQU $fe
DEF SPRITE_PEON_QUEST_3 EQU $ff
