; PEON OF WARCRAFT title: native four-channel MIDI-guide arrangement.
; Generated by tools/build_peon_title_music.py. No streamed PCM.
; 96 sixteenths, tempo 223: approximately 16.73s per loop.
Music_TitleScreen:
	channel_count 4
	channel 1, Music_TitleScreen_Ch1
	channel 2, Music_TitleScreen_Ch2
	channel 3, Music_TitleScreen_Ch3
	channel 4, Music_TitleScreen_Ch4

Music_TitleScreen_Ch1:
	tempo 223
	volume 7, 7
	duty_cycle 2
	vibrato 12, 1, 3
	stereo_panning TRUE, TRUE
	note_type 12, 11, 0
.loop:
	octave 3
	note F#, 2
	note B_, 6
	note D#, 4
	note F_, 4
	note A_, 4
	note E_, 2
	note G#, 2
	note D#, 4
	rest 4
	note F#, 2
	note B_, 12
	note F_, 2
	note A_, 2
	note B_, 4
	note E_, 4
	octave 4
	note B_, 4
	octave 3
	note F#, 2
	note B_, 2
	octave 4
	note D#, 6
	octave 3
	note D#, 6
	note C_, 2
	note D_, 4
	note A_, 2
	octave 4
	note G#, 2
	octave 5
	note C#, 4
	rest 4
	sound_loop 0, .loop

Music_TitleScreen_Ch2:
	duty_cycle 1
	stereo_panning FALSE, TRUE
	note_type 12, 7, 3
.loop:
	octave 2
	note B_, 2
	rest 2
	note B_, 2
	rest 2
	note G#, 2
	rest 2
	note F_, 2
	rest 2
	octave 3
	note D_, 2
	rest 2
	octave 2
	note E_, 2
	rest 2
	note G#, 2
	rest 6
	note B_, 2
	rest 2
	note B_, 2
	rest 2
	octave 3
	note E_, 2
	rest 2
	octave 2
	note B_, 2
	rest 2
	octave 3
	note D_, 2
	rest 2
	octave 2
	note B_, 2
	rest 2
	note A_, 2
	rest 2
	octave 3
	note B_, 2
	rest 2
	note E_, 2
	rest 2
	note D#, 2
	rest 2
	octave 2
	note G#, 2
	rest 2
	note D#, 2
	rest 2
	note G_, 2
	rest 2
	note A_, 2
	rest 2
	octave 4
	note F#, 2
	rest 6
	sound_loop 0, .loop

Music_TitleScreen_Ch3:
	stereo_panning TRUE, TRUE
	note_type 12, 2, 0
.loop:
	octave 3
	note G_, 16
	note G_, 16
	note G_, 16
	rest 4
	note G_, 8
	note D_, 4
	octave 2
	note D_, 16
	note D_, 12
	rest 4
	sound_loop 0, .loop

Music_TitleScreen_Ch4:
	toggle_noise 3
	stereo_panning TRUE, FALSE
	drum_speed 12
.loop:
	drum_note 4, 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 2
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	drum_note 1, 1
	rest 2
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	drum_note 4, 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	rest 2
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 2
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 2
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	drum_note 4, 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	drum_note 4, 1
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	drum_note 4, 1
	rest 1
	drum_note 1, 1
	rest 2
	drum_note 4, 1
	drum_note 1, 1
	drum_note 4, 1
	rest 2
	drum_note 1, 1
	rest 1
	drum_note 4, 1
	rest 1
	sound_loop 0, .loop
