; Original Warcraft item icons: generated by tools/build_peon_item_catalog.py.
; C = real item ID; $fe is a UI-only hearthstone asset selector, not an item.
; Preserves AF/BC/DE/HL and VBK. No inventory, flags or SRAM fields are changed.
; Four row-major BG tiles at bank 0 vTiles2 $28..$2b, palette 5, cols 16..17,
; rows 3..4. Unknown IDs safely use the small pouch. GBC-only ROM presentation.
SECTION "Peon Inventory Item Icons", ROMX

PeonDrawInventoryItemIconFromC::
	push af
	push bc
	push de
	push hl
	ldh a, [rVBK]
	push af
	ldh a, [hCGB]
	and a
	jp z, .Done
	ld e, c
	ld hl, PeonInventoryItemIconLookup
.Find:
	ld a, [hli]
	cp $ff
	jr z, .Fallback
	cp e
	jr z, .Found
	ld bc, 4
	add hl, bc
	jr .Find
.Fallback:
	ld hl, PeonInventoryFallbackIcon
.Found:
	ld a, [hli]
	ld d, [hl]
	ld e, a
	inc hl
	ld a, [hli]
	ld h, [hl]
	ld l, a
	push hl ; keep this item's palette across Get2bpp
	xor a
	ldh [rVBK], a
	ld hl, vTiles2 tile $28
	lb bc, BANK(PeonItemIconCrudeMaceGFX), 4
	call Get2bpp
	pop hl
	ld de, wBGPals1 palette 5
	ld bc, 1 palettes
	ld a, BANK(wBGPals1)
	call FarCopyWRAM
	hlcoord 16, 3
	ld [hl], $28
	inc hl
	ld [hl], $29
	hlcoord 16, 4
	ld [hl], $2a
	inc hl
	ld [hl], $2b
	hlcoord 16, 3, wAttrmap
	ld [hl], 5
	inc hl
	ld [hl], 5
	hlcoord 16, 4, wAttrmap
	ld [hl], 5
	inc hl
	ld [hl], 5
	farcall ApplyPals
	ld a, TRUE
	ldh [hCGBPalUpdate], a
	call WaitBGMap2
.Done:
	pop af
	ldh [rVBK], a
	pop hl
	pop de
	pop bc
	pop af
	ret

PeonInventoryItemIconLookup:
	db POTION
	dw PeonItemIconMinorHealingPotionGFX, PeonItemIconMinorHealingPotionPalette
	db FRESH_WATER
	dw PeonItemIconSpringWaterGFX, PeonItemIconSpringWaterPalette
	db $fe
	dw PeonItemIconHearthstoneGFX, PeonItemIconHearthstonePalette
	db ITEM_19
	dw PeonItemIconCrudeMaceGFX, PeonItemIconCrudeMacePalette
	db ITEM_87
	dw PeonItemIconCrackedMaceGFX, PeonItemIconCrackedMacePalette
	db ITEM_88
	dw PeonItemIconWornMaceGFX, PeonItemIconWornMacePalette
	db ITEM_89
	dw PeonItemIconBarbedClubGFX, PeonItemIconBarbedClubPalette
	db ITEM_8D
	dw PeonItemIconShamanMaceGFX, PeonItemIconShamanMacePalette
	db ITEM_8E
	dw PeonItemIconSpiritMaceGFX, PeonItemIconSpiritMacePalette
	db ITEM_2D
	dw PeonItemIconWoodenShieldGFX, PeonItemIconWoodenShieldPalette
	db ITEM_32
	dw PeonItemIconApprenticeTotemGFX, PeonItemIconApprenticeTotemPalette
	db ITEM_64
	dw PeonItemIconSmallPouchGFX, PeonItemIconSmallPouchPalette
	db ITEM_78
	dw PeonItemIconLeatherBagGFX, PeonItemIconLeatherBagPalette
	db ITEM_91
	dw PeonItemIconSarkothClawGFX, PeonItemIconSarkothClawPalette
	db ITEM_93
	dw PeonItemIconBladeMedallionGFX, PeonItemIconBladeMedallionPalette
	db ITEM_94
	dw PeonItemIconEarthTotemGFX, PeonItemIconEarthTotemPalette
	db $ff
PeonInventoryFallbackIcon:
	dw PeonItemIconSmallPouchGFX, PeonItemIconSmallPouchPalette

PeonItemIconMinorHealingPotionGFX:
	INCBIN "gfx/pack/peon_item_icons/minor_healing_potion.2bpp"
	assert @ - PeonItemIconMinorHealingPotionGFX == 4 * LEN_2BPP_TILE
PeonItemIconMinorHealingPotionPalette:
	INCLUDE "gfx/pack/peon_item_icons/minor_healing_potion.pal"
	assert @ - PeonItemIconMinorHealingPotionPalette == 1 palettes

PeonItemIconSpringWaterGFX:
	INCBIN "gfx/pack/peon_item_icons/spring_water.2bpp"
	assert @ - PeonItemIconSpringWaterGFX == 4 * LEN_2BPP_TILE
PeonItemIconSpringWaterPalette:
	INCLUDE "gfx/pack/peon_item_icons/spring_water.pal"
	assert @ - PeonItemIconSpringWaterPalette == 1 palettes

PeonItemIconHearthstoneGFX:
	INCBIN "gfx/pack/peon_item_icons/hearthstone.2bpp"
	assert @ - PeonItemIconHearthstoneGFX == 4 * LEN_2BPP_TILE
PeonItemIconHearthstonePalette:
	INCLUDE "gfx/pack/peon_item_icons/hearthstone.pal"
	assert @ - PeonItemIconHearthstonePalette == 1 palettes

PeonItemIconCrudeMaceGFX:
	INCBIN "gfx/pack/peon_item_icons/crude_mace.2bpp"
	assert @ - PeonItemIconCrudeMaceGFX == 4 * LEN_2BPP_TILE
PeonItemIconCrudeMacePalette:
	INCLUDE "gfx/pack/peon_item_icons/crude_mace.pal"
	assert @ - PeonItemIconCrudeMacePalette == 1 palettes

PeonItemIconCrackedMaceGFX:
	INCBIN "gfx/pack/peon_item_icons/cracked_mace.2bpp"
	assert @ - PeonItemIconCrackedMaceGFX == 4 * LEN_2BPP_TILE
PeonItemIconCrackedMacePalette:
	INCLUDE "gfx/pack/peon_item_icons/cracked_mace.pal"
	assert @ - PeonItemIconCrackedMacePalette == 1 palettes

PeonItemIconWornMaceGFX:
	INCBIN "gfx/pack/peon_item_icons/worn_mace.2bpp"
	assert @ - PeonItemIconWornMaceGFX == 4 * LEN_2BPP_TILE
PeonItemIconWornMacePalette:
	INCLUDE "gfx/pack/peon_item_icons/worn_mace.pal"
	assert @ - PeonItemIconWornMacePalette == 1 palettes

PeonItemIconBarbedClubGFX:
	INCBIN "gfx/pack/peon_item_icons/barbed_club.2bpp"
	assert @ - PeonItemIconBarbedClubGFX == 4 * LEN_2BPP_TILE
PeonItemIconBarbedClubPalette:
	INCLUDE "gfx/pack/peon_item_icons/barbed_club.pal"
	assert @ - PeonItemIconBarbedClubPalette == 1 palettes

PeonItemIconShamanMaceGFX:
	INCBIN "gfx/pack/peon_item_icons/shaman_mace.2bpp"
	assert @ - PeonItemIconShamanMaceGFX == 4 * LEN_2BPP_TILE
PeonItemIconShamanMacePalette:
	INCLUDE "gfx/pack/peon_item_icons/shaman_mace.pal"
	assert @ - PeonItemIconShamanMacePalette == 1 palettes

PeonItemIconSpiritMaceGFX:
	INCBIN "gfx/pack/peon_item_icons/spirit_mace.2bpp"
	assert @ - PeonItemIconSpiritMaceGFX == 4 * LEN_2BPP_TILE
PeonItemIconSpiritMacePalette:
	INCLUDE "gfx/pack/peon_item_icons/spirit_mace.pal"
	assert @ - PeonItemIconSpiritMacePalette == 1 palettes

PeonItemIconHeavyTrainingMaceGFX:
	INCBIN "gfx/pack/peon_item_icons/heavy_training_mace.2bpp"
	assert @ - PeonItemIconHeavyTrainingMaceGFX == 4 * LEN_2BPP_TILE
PeonItemIconHeavyTrainingMacePalette:
	INCLUDE "gfx/pack/peon_item_icons/heavy_training_mace.pal"
	assert @ - PeonItemIconHeavyTrainingMacePalette == 1 palettes

PeonItemIconWoodenShieldGFX:
	INCBIN "gfx/pack/peon_item_icons/wooden_shield.2bpp"
	assert @ - PeonItemIconWoodenShieldGFX == 4 * LEN_2BPP_TILE
PeonItemIconWoodenShieldPalette:
	INCLUDE "gfx/pack/peon_item_icons/wooden_shield.pal"
	assert @ - PeonItemIconWoodenShieldPalette == 1 palettes

PeonItemIconApprenticeTotemGFX:
	INCBIN "gfx/pack/peon_item_icons/apprentice_totem.2bpp"
	assert @ - PeonItemIconApprenticeTotemGFX == 4 * LEN_2BPP_TILE
PeonItemIconApprenticeTotemPalette:
	INCLUDE "gfx/pack/peon_item_icons/apprentice_totem.pal"
	assert @ - PeonItemIconApprenticeTotemPalette == 1 palettes

PeonItemIconSmallPouchGFX:
	INCBIN "gfx/pack/peon_item_icons/small_pouch.2bpp"
	assert @ - PeonItemIconSmallPouchGFX == 4 * LEN_2BPP_TILE
PeonItemIconSmallPouchPalette:
	INCLUDE "gfx/pack/peon_item_icons/small_pouch.pal"
	assert @ - PeonItemIconSmallPouchPalette == 1 palettes

PeonItemIconLeatherBagGFX:
	INCBIN "gfx/pack/peon_item_icons/leather_bag.2bpp"
	assert @ - PeonItemIconLeatherBagGFX == 4 * LEN_2BPP_TILE
PeonItemIconLeatherBagPalette:
	INCLUDE "gfx/pack/peon_item_icons/leather_bag.pal"
	assert @ - PeonItemIconLeatherBagPalette == 1 palettes

PeonItemIconSarkothClawGFX:
	INCBIN "gfx/pack/peon_item_icons/sarkoth_claw.2bpp"
	assert @ - PeonItemIconSarkothClawGFX == 4 * LEN_2BPP_TILE
PeonItemIconSarkothClawPalette:
	INCLUDE "gfx/pack/peon_item_icons/sarkoth_claw.pal"
	assert @ - PeonItemIconSarkothClawPalette == 1 palettes

PeonItemIconBladeMedallionGFX:
	INCBIN "gfx/pack/peon_item_icons/blade_medallion.2bpp"
	assert @ - PeonItemIconBladeMedallionGFX == 4 * LEN_2BPP_TILE
PeonItemIconBladeMedallionPalette:
	INCLUDE "gfx/pack/peon_item_icons/blade_medallion.pal"
	assert @ - PeonItemIconBladeMedallionPalette == 1 palettes

PeonItemIconMageClothRobeGFX:
	INCBIN "gfx/pack/peon_item_icons/mage_cloth_robe.2bpp"
	assert @ - PeonItemIconMageClothRobeGFX == 4 * LEN_2BPP_TILE
PeonItemIconMageClothRobePalette:
	INCLUDE "gfx/pack/peon_item_icons/mage_cloth_robe.pal"
	assert @ - PeonItemIconMageClothRobePalette == 1 palettes

PeonItemIconMageStaffGFX:
	INCBIN "gfx/pack/peon_item_icons/mage_staff.2bpp"
	assert @ - PeonItemIconMageStaffGFX == 4 * LEN_2BPP_TILE
PeonItemIconMageStaffPalette:
	INCLUDE "gfx/pack/peon_item_icons/mage_staff.pal"
	assert @ - PeonItemIconMageStaffPalette == 1 palettes

PeonItemIconMageWandGFX:
	INCBIN "gfx/pack/peon_item_icons/mage_wand.2bpp"
	assert @ - PeonItemIconMageWandGFX == 4 * LEN_2BPP_TILE
PeonItemIconMageWandPalette:
	INCLUDE "gfx/pack/peon_item_icons/mage_wand.pal"
	assert @ - PeonItemIconMageWandPalette == 1 palettes

PeonItemIconWarriorAxeGFX:
	INCBIN "gfx/pack/peon_item_icons/warrior_axe.2bpp"
	assert @ - PeonItemIconWarriorAxeGFX == 4 * LEN_2BPP_TILE
PeonItemIconWarriorAxePalette:
	INCLUDE "gfx/pack/peon_item_icons/warrior_axe.pal"
	assert @ - PeonItemIconWarriorAxePalette == 1 palettes

PeonItemIconWarriorSwordGFX:
	INCBIN "gfx/pack/peon_item_icons/warrior_sword.2bpp"
	assert @ - PeonItemIconWarriorSwordGFX == 4 * LEN_2BPP_TILE
PeonItemIconWarriorSwordPalette:
	INCLUDE "gfx/pack/peon_item_icons/warrior_sword.pal"
	assert @ - PeonItemIconWarriorSwordPalette == 1 palettes

PeonItemIconWarriorHelmetGFX:
	INCBIN "gfx/pack/peon_item_icons/warrior_helmet.2bpp"
	assert @ - PeonItemIconWarriorHelmetGFX == 4 * LEN_2BPP_TILE
PeonItemIconWarriorHelmetPalette:
	INCLUDE "gfx/pack/peon_item_icons/warrior_helmet.pal"
	assert @ - PeonItemIconWarriorHelmetPalette == 1 palettes

PeonItemIconWarriorMailGFX:
	INCBIN "gfx/pack/peon_item_icons/warrior_mail.2bpp"
	assert @ - PeonItemIconWarriorMailGFX == 4 * LEN_2BPP_TILE
PeonItemIconWarriorMailPalette:
	INCLUDE "gfx/pack/peon_item_icons/warrior_mail.pal"
	assert @ - PeonItemIconWarriorMailPalette == 1 palettes

PeonItemIconRoughBootsGFX:
	INCBIN "gfx/pack/peon_item_icons/rough_boots.2bpp"
	assert @ - PeonItemIconRoughBootsGFX == 4 * LEN_2BPP_TILE
PeonItemIconRoughBootsPalette:
	INCLUDE "gfx/pack/peon_item_icons/rough_boots.pal"
	assert @ - PeonItemIconRoughBootsPalette == 1 palettes

PeonItemIconEarthTotemGFX:
	INCBIN "gfx/pack/peon_item_icons/earth_totem.2bpp"
	assert @ - PeonItemIconEarthTotemGFX == 4 * LEN_2BPP_TILE
PeonItemIconEarthTotemPalette:
	INCLUDE "gfx/pack/peon_item_icons/earth_totem.pal"
	assert @ - PeonItemIconEarthTotemPalette == 1 palettes

PeonItemIconLightningTotemGFX:
	INCBIN "gfx/pack/peon_item_icons/lightning_totem.2bpp"
	assert @ - PeonItemIconLightningTotemGFX == 4 * LEN_2BPP_TILE
PeonItemIconLightningTotemPalette:
	INCLUDE "gfx/pack/peon_item_icons/lightning_totem.pal"
	assert @ - PeonItemIconLightningTotemPalette == 1 palettes

PeonItemIconRockbiterWeaponGFX:
	INCBIN "gfx/pack/peon_item_icons/rockbiter_weapon.2bpp"
	assert @ - PeonItemIconRockbiterWeaponGFX == 4 * LEN_2BPP_TILE
PeonItemIconRockbiterWeaponPalette:
	INCLUDE "gfx/pack/peon_item_icons/rockbiter_weapon.pal"
	assert @ - PeonItemIconRockbiterWeaponPalette == 1 palettes

PeonItemIconEarthShockGFX:
	INCBIN "gfx/pack/peon_item_icons/earth_shock.2bpp"
	assert @ - PeonItemIconEarthShockGFX == 4 * LEN_2BPP_TILE
PeonItemIconEarthShockPalette:
	INCLUDE "gfx/pack/peon_item_icons/earth_shock.pal"
	assert @ - PeonItemIconEarthShockPalette == 1 palettes

PeonItemIconHealingWaveGFX:
	INCBIN "gfx/pack/peon_item_icons/healing_wave.2bpp"
	assert @ - PeonItemIconHealingWaveGFX == 4 * LEN_2BPP_TILE
PeonItemIconHealingWavePalette:
	INCLUDE "gfx/pack/peon_item_icons/healing_wave.pal"
	assert @ - PeonItemIconHealingWavePalette == 1 palettes

PeonItemIconLightningShieldGFX:
	INCBIN "gfx/pack/peon_item_icons/lightning_shield.2bpp"
	assert @ - PeonItemIconLightningShieldGFX == 4 * LEN_2BPP_TILE
PeonItemIconLightningShieldPalette:
	INCLUDE "gfx/pack/peon_item_icons/lightning_shield.pal"
	assert @ - PeonItemIconLightningShieldPalette == 1 palettes

PeonItemIconStrengthOfEarthGFX:
	INCBIN "gfx/pack/peon_item_icons/strength_of_earth.2bpp"
	assert @ - PeonItemIconStrengthOfEarthGFX == 4 * LEN_2BPP_TILE
PeonItemIconStrengthOfEarthPalette:
	INCLUDE "gfx/pack/peon_item_icons/strength_of_earth.pal"
	assert @ - PeonItemIconStrengthOfEarthPalette == 1 palettes

PeonItemIconPurgeGFX:
	INCBIN "gfx/pack/peon_item_icons/purge.2bpp"
	assert @ - PeonItemIconPurgeGFX == 4 * LEN_2BPP_TILE
PeonItemIconPurgePalette:
	INCLUDE "gfx/pack/peon_item_icons/purge.pal"
	assert @ - PeonItemIconPurgePalette == 1 palettes
