; Generated by tools/build_peon_sfx.py.
; Original short pulse/noise imitations; no imported audio PCM.
SECTION "Peon Sound Effects", ROMX

; Wood-and-metal mace impact / BONK
PeonSfx_MaceImpact:
	channel_count 2
	channel 5, PeonSfx_MaceImpact_Ch5
	channel 8, PeonSfx_MaceImpact_Ch8

PeonSfx_MaceImpact_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 10, 1, 1300
	square_note 3, 8, 2, 900
	square_note 4, 4, 1, 350
	sound_ret

PeonSfx_MaceImpact_Ch8:
	noise_note 1, 12, 1, 82
	noise_note 3, 9, 2, 100
	noise_note 4, 5, 1, 112
	sound_ret

; Quiet rising charge, sharp broadband crack, descending electric hiss.
; Original override: tools/build_peon_valley_sfx.py.
PeonSfx_Lightning:
	channel_count 2
	channel 5, PeonSfx_Lightning_Ch5
	channel 8, PeonSfx_Lightning_Ch8

PeonSfx_Lightning_Ch5:
	duty_cycle 0
	pitch_sweep 0, 8
	square_note 2, 2, 2, 1100
	square_note 2, 3, 2, 1480
	square_note 1, 4, 1, 1750
	square_note 1, 4, 1, 850
	square_note 2, 2, 1, 1740
	square_note 3, 1, 1, 1900
	square_note 4, 0, 0, 0
	sound_ret

PeonSfx_Lightning_Ch8:
	noise_note 2, 3, 3, 53
	noise_note 2, 5, 2, 37
	noise_note 1, 7, 1, 20
	noise_note 1, 12, 1, 2
	noise_note 2, 9, 1, 36
	noise_note 3, 6, 2, 53
	noise_note 4, 3, 1, 69
	noise_note 4, 2, 1, 84
	sound_ret

; Flame ignition, fiery rush and low impact
PeonSfx_Firebolt:
	channel_count 2
	channel 5, PeonSfx_Firebolt_Ch5
	channel 8, PeonSfx_Firebolt_Ch8

PeonSfx_Firebolt_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 5, 2, 1100
	square_note 3, 8, 2, 1500
	square_note 4, 9, 1, 1800
	square_note 5, 7, 1, 1300
	square_note 3, 3, 1, 700
	sound_ret

PeonSfx_Firebolt_Ch8:
	noise_note 3, 6, 2, 53
	noise_note 4, 10, 2, 34
	noise_note 5, 11, 1, 67
	noise_note 6, 5, 1, 83
	sound_ret

; Short bubbling toxic hiss
PeonSfx_Poison:
	channel_count 1
	channel 8, PeonSfx_Poison_Ch8

PeonSfx_Poison_Ch8:
	noise_note 2, 4, 2, 68
	noise_note 3, 8, 2, 52
	noise_note 3, 6, 1, 53
	noise_note 4, 3, 1, 68
	sound_ret

; Quick piercing sting with a dry click
PeonSfx_PoisonSting:
	channel_count 2
	channel 5, PeonSfx_PoisonSting_Ch5
	channel 8, PeonSfx_PoisonSting_Ch8

PeonSfx_PoisonSting_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 1, 7, 1, 1850
	square_note 2, 9, 1, 1700
	square_note 3, 3, 1, 1300
	sound_ret

PeonSfx_PoisonSting_Ch8:
	noise_note 1, 8, 1, 34
	noise_note 2, 6, 1, 52
	noise_note 3, 2, 1, 69
	sound_ret

; Two small metal coin chimes
PeonSfx_Coins:
	channel_count 2
	channel 5, PeonSfx_Coins_Ch5
	channel 6, PeonSfx_Coins_Ch6

PeonSfx_Coins_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 2, 7, 1, 1880
	square_note 2, 9, 1, 1936
	square_note 5, 4, 1, 1980
	sound_ret

PeonSfx_Coins_Ch6:
	duty_cycle 2
	square_note 2, 0, 0, 0
	square_note 2, 5, 1, 1910
	square_note 5, 3, 1, 1958
	sound_ret

; Quiet tactile menu click
PeonSfx_Menu:
	channel_count 1
	channel 8, PeonSfx_Menu_Ch8

PeonSfx_Menu_Ch8:
	noise_note 1, 4, 1, 53
	noise_note 2, 2, 1, 68
	sound_ret

; Leather flap and soft strap rustle
PeonSfx_LeatherBag:
	channel_count 1
	channel 8, PeonSfx_LeatherBag_Ch8

PeonSfx_LeatherBag_Ch8:
	noise_note 2, 3, 2, 69
	noise_note 3, 5, 2, 53
	noise_note 2, 4, 1, 70
	noise_note 3, 2, 1, 84
	sound_ret

; Two brief warm low-register grunts with a gravelly noise layer.
; Original override: tools/build_peon_valley_sfx.py.
PeonSfx_BoarGrunt:
	channel_count 2
	channel 5, PeonSfx_BoarGrunt_Ch5
	channel 8, PeonSfx_BoarGrunt_Ch8

PeonSfx_BoarGrunt_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 8, 2, 1280
	square_note 2, 9, 1, 940
	square_note 3, 5, 1, 550
	square_note 2, 0, 0, 0
	square_note 2, 9, 1, 1100
	square_note 3, 6, 1, 760
	square_note 2, 3, 1, 450
	sound_ret

PeonSfx_BoarGrunt_Ch8:
	noise_note 2, 4, 2, 53
	noise_note 2, 6, 1, 83
	noise_note 3, 3, 1, 100
	noise_note 2, 0, 0, 0
	noise_note 2, 5, 1, 69
	noise_note 3, 4, 1, 84
	noise_note 2, 2, 1, 101
	sound_ret
