; Generated by tools/build_peon_sfx.py.
; Original short pulse/noise imitations; no imported audio PCM.
SECTION "Peon Sound Effects", ROMX

; Wood-and-metal mace impact / BONK
PeonSfx_MaceImpact:
	channel_count 2
	channel 5, PeonSfx_MaceImpact_Ch5
	channel 8, PeonSfx_MaceImpact_Ch8

PeonSfx_MaceImpact_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 10, 1, 1300
	square_note 3, 8, 2, 900
	square_note 4, 4, 1, 350
	sound_ret

PeonSfx_MaceImpact_Ch8:
	noise_note 1, 12, 1, 82
	noise_note 3, 9, 2, 100
	noise_note 4, 5, 1, 112
	sound_ret

; Quiet rising charge, sharp broadband crack, descending electric hiss.
; Original override: tools/build_peon_valley_sfx.py.
PeonSfx_Lightning:
	channel_count 2
	channel 5, PeonSfx_Lightning_Ch5
	channel 8, PeonSfx_Lightning_Ch8

PeonSfx_Lightning_Ch5:
	duty_cycle 0
	pitch_sweep 0, 8
	square_note 2, 2, 2, 1100
	square_note 2, 3, 2, 1480
	square_note 1, 4, 1, 1750
	square_note 1, 4, 1, 850
	square_note 2, 2, 1, 1740
	square_note 3, 1, 1, 1900
	square_note 4, 0, 0, 0
	sound_ret

PeonSfx_Lightning_Ch8:
	noise_note 2, 3, 3, 53
	noise_note 2, 5, 2, 37
	noise_note 1, 7, 1, 20
	noise_note 1, 12, 1, 2
	noise_note 2, 9, 1, 36
	noise_note 3, 6, 2, 53
	noise_note 4, 3, 1, 69
	noise_note 4, 2, 1, 84
	sound_ret

; Flame ignition, fiery rush and low impact
PeonSfx_Firebolt:
	channel_count 2
	channel 5, PeonSfx_Firebolt_Ch5
	channel 8, PeonSfx_Firebolt_Ch8

PeonSfx_Firebolt_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 5, 2, 1100
	square_note 3, 8, 2, 1500
	square_note 4, 9, 1, 1800
	square_note 5, 7, 1, 1300
	square_note 3, 3, 1, 700
	sound_ret

PeonSfx_Firebolt_Ch8:
	noise_note 3, 6, 2, 53
	noise_note 4, 10, 2, 34
	noise_note 5, 11, 1, 67
	noise_note 6, 5, 1, 83
	sound_ret

; Short bubbling toxic hiss
PeonSfx_Poison:
	channel_count 1
	channel 8, PeonSfx_Poison_Ch8

PeonSfx_Poison_Ch8:
	noise_note 2, 4, 2, 68
	noise_note 3, 8, 2, 52
	noise_note 3, 6, 1, 53
	noise_note 4, 3, 1, 68
	sound_ret

; Quick piercing sting with a dry click
PeonSfx_PoisonSting:
	channel_count 2
	channel 5, PeonSfx_PoisonSting_Ch5
	channel 8, PeonSfx_PoisonSting_Ch8

PeonSfx_PoisonSting_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 1, 7, 1, 1850
	square_note 2, 9, 1, 1700
	square_note 3, 3, 1, 1300
	sound_ret

PeonSfx_PoisonSting_Ch8:
	noise_note 1, 8, 1, 34
	noise_note 2, 6, 1, 52
	noise_note 3, 2, 1, 69
	sound_ret

; Two small metal coin chimes
PeonSfx_Coins:
	channel_count 2
	channel 5, PeonSfx_Coins_Ch5
	channel 6, PeonSfx_Coins_Ch6

PeonSfx_Coins_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 2, 7, 1, 1880
	square_note 2, 9, 1, 1936
	square_note 5, 4, 1, 1980
	sound_ret

PeonSfx_Coins_Ch6:
	duty_cycle 2
	square_note 2, 0, 0, 0
	square_note 2, 5, 1, 1910
	square_note 5, 3, 1, 1958
	sound_ret

; Quiet tactile menu click
PeonSfx_Menu:
	channel_count 1
	channel 8, PeonSfx_Menu_Ch8

PeonSfx_Menu_Ch8:
	noise_note 1, 4, 1, 53
	noise_note 2, 2, 1, 68
	sound_ret

; Leather flap and soft strap rustle
PeonSfx_LeatherBag:
	channel_count 1
	channel 8, PeonSfx_LeatherBag_Ch8

PeonSfx_LeatherBag_Ch8:
	noise_note 2, 3, 2, 69
	noise_note 3, 5, 2, 53
	noise_note 2, 4, 1, 70
	noise_note 3, 2, 1, 84
	sound_ret

; Two brief warm low-register grunts with a gravelly noise layer.
; Original override: tools/build_peon_valley_sfx.py.
PeonSfx_BoarGrunt:
	channel_count 2
	channel 5, PeonSfx_BoarGrunt_Ch5
	channel 8, PeonSfx_BoarGrunt_Ch8

PeonSfx_BoarGrunt_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 8, 2, 1280
	square_note 2, 9, 1, 940
	square_note 3, 5, 1, 550
	square_note 2, 0, 0, 0
	square_note 2, 9, 1, 1100
	square_note 3, 6, 1, 760
	square_note 2, 3, 1, 450
	sound_ret

PeonSfx_BoarGrunt_Ch8:
	noise_note 2, 4, 2, 53
	noise_note 2, 6, 1, 83
	noise_note 3, 3, 1, 100
	noise_note 2, 0, 0, 0
	noise_note 2, 5, 1, 69
	noise_note 3, 4, 1, 84
	noise_note 2, 2, 1, 101
	sound_ret

; BEGIN PEON AUDIO EXPANSION
; Generated by tools/build_peon_audio_expansion.py; original synthesis.
SECTION "Peon Audio Expansion", ROMX

; Small ascending bell with a quiet harmonic.
PeonSfx_LevelUp:
	channel_count 2
	channel 5, PeonSfx_LevelUp_Ch5
	channel 6, PeonSfx_LevelUp_Ch6

PeonSfx_LevelUp_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 2, 7, 2, 1760
	square_note 2, 7, 2, 1818
	square_note 3, 6, 2, 1856
	square_note 7, 5, 2, 1884
	sound_ret

PeonSfx_LevelUp_Ch6:
	duty_cycle 1
	square_note 2, 3, 2, 1617
	square_note 2, 3, 2, 1695
	square_note 3, 3, 2, 1758
	square_note 7, 2, 2, 1804
	sound_ret

; Quiet parchment tap followed by a rising confirmation.
PeonSfx_QuestAccept:
	channel_count 2
	channel 5, PeonSfx_QuestAccept_Ch5
	channel 8, PeonSfx_QuestAccept_Ch8

PeonSfx_QuestAccept_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 4, 1, 1510
	square_note 4, 5, 2, 1740
	square_note 3, 2, 1, 1800
	sound_ret

PeonSfx_QuestAccept_Ch8:
	noise_note 1, 3, 1, 84
	noise_note 2, 2, 1, 101
	sound_ret

; Two restrained bright notes announcing a completed objective.
PeonSfx_QuestReady:
	channel_count 1
	channel 5, PeonSfx_QuestReady_Ch5

PeonSfx_QuestReady_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 2, 5, 1, 1835
	square_note 1, 0, 0, 0
	square_note 5, 4, 2, 1900
	sound_ret

; Warm resolved triad with a small metallic overtone.
PeonSfx_QuestReward:
	channel_count 2
	channel 5, PeonSfx_QuestReward_Ch5
	channel 6, PeonSfx_QuestReward_Ch6

PeonSfx_QuestReward_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 2, 6, 1, 1740
	square_note 2, 6, 1, 1818
	square_note 6, 4, 2, 1884
	sound_ret

PeonSfx_QuestReward_Ch6:
	duty_cycle 2
	square_note 2, 2, 1, 1884
	square_note 2, 3, 1, 1914
	square_note 6, 2, 2, 1958
	sound_ret

; Soft upward light with a gentle airy decay.
PeonSfx_Healing:
	channel_count 2
	channel 5, PeonSfx_Healing_Ch5
	channel 8, PeonSfx_Healing_Ch8

PeonSfx_Healing_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 3, 3, 2, 1548
	square_note 3, 4, 2, 1695
	square_note 5, 4, 2, 1804
	square_note 5, 2, 2, 1884
	sound_ret

PeonSfx_Healing_Ch8:
	noise_note 3, 2, 2, 53
	noise_note 3, 3, 2, 69
	noise_note 5, 2, 2, 84
	noise_note 5, 1, 1, 101
	sound_ret

; Bottle pop, two liquid bubbles and a short restoration note.
PeonSfx_Potion:
	channel_count 2
	channel 5, PeonSfx_Potion_Ch5
	channel 8, PeonSfx_Potion_Ch8

PeonSfx_Potion_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 1, 4, 1, 1730
	square_note 2, 3, 1, 1250
	square_note 2, 4, 1, 1530
	square_note 5, 3, 2, 1804
	sound_ret

PeonSfx_Potion_Ch8:
	noise_note 1, 5, 1, 37
	noise_note 2, 3, 1, 83
	noise_note 2, 3, 1, 67
	noise_note 5, 1, 2, 101
	sound_ret

; Two small dry bread crunches; no melodic fanfare.
PeonSfx_Food:
	channel_count 1
	channel 8, PeonSfx_Food_Ch8

PeonSfx_Food_Ch8:
	noise_note 2, 4, 1, 67
	noise_note 2, 2, 1, 101
	noise_note 2, 0, 0, 0
	noise_note 2, 4, 1, 68
	noise_note 3, 2, 1, 101
	sound_ret

; Wood touches ground, followed by a low shamanic resonance.
PeonSfx_TotemPlace:
	channel_count 2
	channel 5, PeonSfx_TotemPlace_Ch5
	channel 8, PeonSfx_TotemPlace_Ch8

PeonSfx_TotemPlace_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 1, 7, 1, 920
	square_note 3, 4, 2, 460
	square_note 5, 3, 2, 1180
	square_note 4, 2, 2, 1510
	sound_ret

PeonSfx_TotemPlace_Ch8:
	noise_note 1, 6, 1, 67
	noise_note 3, 3, 1, 100
	noise_note 5, 1, 2, 117
	sound_ret

; A rising then settling magical shimmer for the existing inn return.
PeonSfx_Hearthstone:
	channel_count 2
	channel 5, PeonSfx_Hearthstone_Ch5
	channel 8, PeonSfx_Hearthstone_Ch8

PeonSfx_Hearthstone_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 3, 3, 2, 1460
	square_note 3, 4, 2, 1660
	square_note 3, 5, 2, 1818
	square_note 4, 5, 2, 1914
	square_note 4, 3, 2, 1856
	square_note 6, 2, 2, 1740
	sound_ret

PeonSfx_Hearthstone_Ch8:
	noise_note 3, 2, 2, 69
	noise_note 3, 3, 2, 53
	noise_note 3, 3, 2, 37
	noise_note 4, 2, 2, 53
	noise_note 4, 2, 2, 69
	noise_note 6, 1, 1, 101
	sound_ret

; Brief descending acknowledgement; no full battle music theme.
PeonSfx_Defeat:
	channel_count 1
	channel 5, PeonSfx_Defeat_Ch5

PeonSfx_Defeat_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 3, 5, 2, 1510
	square_note 3, 4, 2, 1280
	square_note 6, 2, 2, 850
	sound_ret

; Three compact upward notes after a won encounter.
PeonSfx_Victory:
	channel_count 1
	channel 5, PeonSfx_Victory_Ch5

PeonSfx_Victory_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 2, 5, 1, 1660
	square_note 2, 5, 1, 1760
	square_note 5, 4, 2, 1856
	sound_ret

; Chitin clicks and a dry scraping hiss, distinct from Poison Sting.
PeonSfx_ScorpidRattle:
	channel_count 2
	channel 5, PeonSfx_ScorpidRattle_Ch5
	channel 8, PeonSfx_ScorpidRattle_Ch8

PeonSfx_ScorpidRattle_Ch5:
	duty_cycle 0
	pitch_sweep 0, 8
	square_note 1, 2, 1, 1810
	square_note 2, 0, 0, 0
	square_note 1, 2, 1, 1680
	square_note 5, 1, 1, 1120
	sound_ret

PeonSfx_ScorpidRattle_Ch8:
	noise_note 1, 7, 1, 36
	noise_note 2, 3, 1, 69
	noise_note 1, 6, 1, 52
	noise_note 5, 3, 2, 83
	sound_ret

; Thin, uneven upward squeal with a short raspy tail.
PeonSfx_ImpYelp:
	channel_count 2
	channel 5, PeonSfx_ImpYelp_Ch5
	channel 8, PeonSfx_ImpYelp_Ch8

PeonSfx_ImpYelp_Ch5:
	duty_cycle 0
	pitch_sweep 0, 8
	square_note 2, 5, 1, 1440
	square_note 2, 6, 1, 1810
	square_note 1, 5, 1, 1660
	square_note 2, 6, 1, 1870
	square_note 4, 3, 2, 1390
	sound_ret

PeonSfx_ImpYelp_Ch8:
	noise_note 2, 2, 1, 45
	noise_note 2, 3, 1, 29
	noise_note 1, 2, 1, 44
	noise_note 2, 3, 1, 28
	noise_note 4, 2, 2, 61
	sound_ret

; Longer throat growl rising into one low bark; no copied creature cry.
PeonSfx_WolfGrowl:
	channel_count 2
	channel 5, PeonSfx_WolfGrowl_Ch5
	channel 8, PeonSfx_WolfGrowl_Ch8

PeonSfx_WolfGrowl_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 4, 5, 2, 550
	square_note 4, 6, 2, 780
	square_note 2, 8, 1, 1260
	square_note 3, 5, 1, 920
	square_note 4, 2, 2, 450
	sound_ret

PeonSfx_WolfGrowl_Ch8:
	noise_note 4, 3, 2, 100
	noise_note 4, 4, 2, 84
	noise_note 2, 6, 1, 53
	noise_note 3, 4, 1, 84
	noise_note 4, 2, 2, 101
	sound_ret

; Two liquid drops and a quiet flowing water tail.
PeonSfx_Water:
	channel_count 2
	channel 5, PeonSfx_Water_Ch5
	channel 8, PeonSfx_Water_Ch8

PeonSfx_Water_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 2, 3, 1, 1740
	square_note 2, 4, 1, 1510
	square_note 2, 3, 1, 1818
	square_note 5, 2, 2, 1617
	sound_ret

PeonSfx_Water_Ch8:
	noise_note 2, 2, 2, 53
	noise_note 2, 3, 1, 69
	noise_note 2, 2, 2, 53
	noise_note 5, 1, 2, 84
	sound_ret

; Brittle bright ice crack fading into a cold fine hiss.
PeonSfx_Frost:
	channel_count 2
	channel 5, PeonSfx_Frost_Ch5
	channel 8, PeonSfx_Frost_Ch8

PeonSfx_Frost_Ch5:
	duty_cycle 0
	pitch_sweep 0, 8
	square_note 1, 5, 1, 1958
	square_note 2, 4, 1, 1900
	square_note 3, 3, 1, 1835
	square_note 5, 1, 2, 1740
	sound_ret

PeonSfx_Frost_Ch8:
	noise_note 1, 7, 1, 20
	noise_note 2, 5, 1, 36
	noise_note 3, 3, 2, 53
	noise_note 5, 1, 2, 69
	sound_ret

; Low stone knock and coarse settling rubble.
PeonSfx_Earth:
	channel_count 2
	channel 5, PeonSfx_Earth_Ch5
	channel 8, PeonSfx_Earth_Ch8

PeonSfx_Earth_Ch5:
	duty_cycle 2
	pitch_sweep 0, 8
	square_note 1, 7, 1, 1120
	square_note 3, 6, 1, 740
	square_note 5, 3, 2, 350
	sound_ret

PeonSfx_Earth_Ch8:
	noise_note 1, 8, 1, 52
	noise_note 3, 5, 1, 84
	noise_note 5, 2, 2, 101
	sound_ret

; Quick stripping sweep with a clean magical release.
PeonSfx_Purge:
	channel_count 2
	channel 5, PeonSfx_Purge_Ch5
	channel 8, PeonSfx_Purge_Ch8

PeonSfx_Purge_Ch5:
	duty_cycle 0
	pitch_sweep 0, 8
	square_note 2, 4, 1, 1900
	square_note 2, 5, 1, 1740
	square_note 3, 3, 1, 1510
	square_note 4, 2, 2, 1100
	sound_ret

PeonSfx_Purge_Ch8:
	noise_note 2, 3, 1, 37
	noise_note 2, 4, 1, 53
	noise_note 3, 3, 1, 69
	noise_note 4, 1, 2, 101
	sound_ret

; Soft wooden resonance and a short leafy breeze.
PeonSfx_Nature:
	channel_count 2
	channel 5, PeonSfx_Nature_Ch5
	channel 8, PeonSfx_Nature_Ch8

PeonSfx_Nature_Ch5:
	duty_cycle 1
	pitch_sweep 0, 8
	square_note 3, 3, 2, 1460
	square_note 3, 4, 2, 1695
	square_note 5, 3, 2, 1760
	sound_ret

PeonSfx_Nature_Ch8:
	noise_note 3, 2, 2, 84
	noise_note 3, 3, 2, 69
	noise_note 5, 1, 2, 101
	sound_ret
; END PEON AUDIO EXPANSION
