#!/usr/bin/env python3
"""Generate original Warcraft-inspired Game Boy sound effects.

These are newly authored pulse/noise gestures, not copied Blizzard recordings.
Existing SFX IDs are connected to these headers by the engine integration.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'references/generated/durotar_v021/sound_effects'

# Each note is (raw engine duration, volume, envelope decay, hardware frequency).
# The native SFX engine adds one frame to each raw duration at its default speed.
EFFECTS = [
    ('mace_bonk', 'PeonSfx_MaceImpact', 'SFX_POUND', 'Wood-and-metal mace impact / BONK', [
        (5, 2, [(2, 10, 1, 1300), (3, 8, 2, 900), (4, 4, 1, 350)]),
        (8, None, [(1, 12, 1, 0x52), (3, 9, 2, 0x64), (4, 5, 1, 0x70)]),
    ]),
    ('lightning_bolt', 'PeonSfx_Lightning', 'SFX_THUNDERSHOCK', 'Lightning charge, crack and electric tail', [
        (5, 0, [(2, 7, 1, 1792), (3, 11, 1, 1900), (1, 8, 1, 1100),
                (3, 12, 1, 1970), (2, 9, 1, 1720), (3, 10, 1, 1930),
                (4, 6, 1, 1870), (6, 3, 1, 1540)]),
        (8, None, [(3, 9, 1, 0x14), (2, 11, 1, 0x25), (3, 12, 1, 0x04),
                   (4, 9, 1, 0x36), (5, 6, 1, 0x45), (7, 3, 1, 0x54)]),
    ]),
    ('firebolt', 'PeonSfx_Firebolt', 'SFX_EMBER', 'Flame ignition, fiery rush and low impact', [
        (5, 2, [(2, 5, 2, 1100), (3, 8, 2, 1500), (4, 9, 1, 1800),
                (5, 7, 1, 1300), (3, 3, 1, 700)]),
        (8, None, [(3, 6, 2, 0x35), (4, 10, 2, 0x22),
                   (5, 11, 1, 0x43), (6, 5, 1, 0x53)]),
    ]),
    ('poison', 'PeonSfx_Poison', 'SFX_POISON', 'Short bubbling toxic hiss', [
        (8, None, [(2, 4, 2, 0x44), (3, 8, 2, 0x34),
                   (3, 6, 1, 0x35), (4, 3, 1, 0x44)]),
    ]),
    ('scorpid_sting', 'PeonSfx_PoisonSting', 'SFX_POISON_STING', 'Quick piercing sting with a dry click', [
        (5, 1, [(1, 7, 1, 1850), (2, 9, 1, 1700), (3, 3, 1, 1300)]),
        (8, None, [(1, 8, 1, 0x22), (2, 6, 1, 0x34), (3, 2, 1, 0x45)]),
    ]),
    ('coins', 'PeonSfx_Coins', 'SFX_TRANSACTION', 'Two small metal coin chimes', [
        (5, 1, [(2, 7, 1, 1880), (2, 9, 1, 1936), (5, 4, 1, 1980)]),
        (6, 2, [(2, 0, 0, 0), (2, 5, 1, 1910), (5, 3, 1, 1958)]),
    ]),
    ('menu', 'PeonSfx_Menu', 'SFX_MENU', 'Quiet tactile menu click', [
        (8, None, [(1, 4, 1, 0x35), (2, 2, 1, 0x44)]),
    ]),
    ('leather_bag', 'PeonSfx_LeatherBag', 'SFX_SWITCH_POCKETS', 'Leather flap and soft strap rustle', [
        (8, None, [(2, 3, 2, 0x45), (3, 5, 2, 0x35),
                   (2, 4, 1, 0x46), (3, 2, 1, 0x54)]),
    ]),
]


def main():
    lines = ['; Generated by tools/build_peon_sfx.py.',
             '; Original short pulse/noise imitations; no imported audio PCM.',
             'SECTION "Peon Sound Effects", ROMX']
    manifest = []
    for name, label, constant, description, channels in EFFECTS:
        lines += ['', f'; {description}', label + ':', f'\tchannel_count {len(channels)}']
        lines += [f'\tchannel {channel}, {label}_Ch{channel}' for channel, _duty, _notes in channels]
        longest = 0
        for channel, duty, notes in channels:
            lines += ['', f'{label}_Ch{channel}:']
            if duty is not None:
                lines.append(f'\tduty_cycle {duty}')
            if channel == 5:
                lines.append('\tpitch_sweep 0, 8')
            for duration, volume, decay, frequency in notes:
                assert 0 <= duration < 0xd0 and 0 <= volume <= 15 and 0 <= decay <= 7
                assert 0 <= frequency <= (255 if channel == 8 else 2047)
                command = 'noise_note' if channel == 8 else 'square_note'
                lines.append(f'\t{command} {duration}, {volume}, {decay}, {frequency}')
            lines.append('\tsound_ret')
            longest = max(longest, sum(note[0] + 1 for note in notes))
        assert longest <= 40, name
        manifest.append({'name': name, 'header': label, 'existing_sfx_id': constant,
                         'description': description, 'channels': [c[0] for c in channels],
                         'estimated_engine_frames': longest, 'estimated_seconds': longest / 60})
    (ROOT / 'audio/peon_sfx.asm').write_text('\n'.join(lines) + '\n')
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / 'design.json').write_text(json.dumps({'effects': manifest,
        'source': 'Original native synthesis inspired by Warcraft sound categories',
        'reference_access': 'Wowhead Classic sounds catalog denied by network proxy; no samples auditioned/copied'},
        indent=2) + '\n')
    print(json.dumps(manifest, indent=2))


if __name__ == '__main__':
    main()
