#!/usr/bin/env python3
"""Project current compiled maps onto their existing native atlas thumbnails.

This does not author a new Valley layout, change collision geometry, or draw
a requested seven-screen overview. Lookup tables use the current map sizes
and the existing ImageOps.contain(156,100) thumbnail transform.
"""
from pathlib import Path
import hashlib
import json
import re
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "references/generated/valley_layout_update/atlas"
SPECS = [("DEN", "TheDen", "THE_DEN"), ("VALLEY", "ValleyOfTrials", "VALLEY_OF_TRIALS"),
         ("ROAD", "DurotarRoad", "DUROTAR_ROAD"), ("SENJIN", "SenjinVillage", "SENJIN_VILLAGE"),
         ("RAZOR", "RazorHill", "RAZOR_HILL"), ("ORGRIMMAR", "OrgrimmarGate", "ORGRIMMAR_GATE"),
         ("CAVERN", "BurningBladeCavern", "BURNING_BLADE_CAVERN")]
ROOM_IDS = {"PEON_TROLL_HUT": 21, "PEON_ORC_HUT": 22, "PEON_ORC_INN": 23, "PEON_TROLL_INN": 24}
AVATAR = ["00333300", "03111130", "31111113", "31311313", "31111113", "03133130", "00322300", "03222230"]
PALETTE = [(31, 31, 31), (15, 22, 8), (18, 11, 6), (0, 0, 0)]


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    text = (ROOT / "constants/map_constants.asm").read_text()
    asm = ["; Current actual map geometry only. Generated by build_peon_atlas_objectives.py.",
           "PeonAtlasProjectionTable:"]
    rows, manifest = [], {"pages": {}, "doors": [], "avatar": {"size": [8, 8], "palette": 6,
        "rgb555": PALETTE, "tile": 2, "vram": "bank0 $8020..$802f", "meaning": "Representational green peon head; not the full overworld sprite."}}
    for page, (ident, name, constant) in enumerate(SPECS):
        match = re.search(rf"map_const\s+{constant},\s*(\d+),\s*(\d+)", text)
        assert match, constant
        w, h = map(int, match.groups())
        assert len((ROOT / f"maps/{name}.blk").read_bytes()) == w * h
        source_size = (w * 32, h * 32)
        thumb = ImageOps.contain(Image.new("L", source_size), (156, 100), Image.Resampling.NEAREST)
        offset = ((160 - thumb.width) // 2, 16 + (104 - thumb.height) // 2)
        xs = [round(offset[0] + (x * 16 + 8) * thumb.width / source_size[0]) for x in range(w * 2)]
        ys = [round(offset[1] + (y * 16 + 8) * thumb.height / source_size[1]) for y in range(h * 2)]
        asm += [f"\tdb {w * 2}, {h * 2}", f"\tdw PeonAtlas{ident}X, PeonAtlas{ident}Y"]
        rows += [f"PeonAtlas{ident}X:", "\tdb " + ", ".join(map(str, xs)),
                 f"PeonAtlas{ident}Y:", "\tdb " + ", ".join(map(str, ys))]
        manifest["pages"][ident] = {"page": page, "map_number": page + 14, "map": name,
            "collision_size": [w * 2, h * 2], "source_size": source_size,
            "thumbnail_size": thumb.size, "thumbnail_offset": offset, "x_centers": xs, "y_centers": ys}
        warps = re.findall(r"warp_event\s+(\d+),\s*(\d+),\s*(\w+),\s*(-?\d+)", (ROOT / f"maps/{name}.asm").read_text())
        for index, (x, y, dest, _) in enumerate(warps, 1):
            if dest in ROOM_IDS:
                manifest["doors"].append({"room": ROOM_IDS[dest], "map": page + 14,
                    "warp": index, "xy": [int(x), int(y)]})
    asm += rows + ["PeonAtlasDoorTable:"]
    for door in manifest["doors"]:
        asm += ["\tdb " + ", ".join(map(str, [door["room"], door["map"], door["warp"], *door["xy"]]))]
    asm += ["\tdb 0"]
    # Objective coordinates are the real interactable cells, not inferred
    # concept points. A cave entrance is a truthful route marker for Yarrog.
    coords = {"LAZY": ("TheDen", r"object_event\s+(\d+),\s*(\d+),[^\n]+TheDenLazyPeonScript"),
              "SARKOTH": ("ValleyOfTrials", r"object_event\s+(\d+),\s*(\d+),[^\n]+ValleySarkothScript"),
              "YARROG": ("BurningBladeCavern", r"object_event\s+(\d+),\s*(\d+),[^\n]+BurningBladeYarrogScript"),
              "CAVE_ENTRANCE": ("ValleyOfTrials", r"warp_event\s+(\d+),\s*(\d+),\s*BURNING_BLADE_CAVERN"),
              **{f"CACTUS{i}": ("ValleyOfTrials", rf"bg_event\s+(\d+),\s*(\d+),[^\n]+PeonCactus{i}\b") for i in (1, 2, 3)}}
    manifest["objectives"] = {}
    for key, (name, pattern) in coords.items():
        found = re.search(pattern, (ROOT / f"maps/{name}.asm").read_text())
        assert found, (key, pattern)
        x, y = map(int, found.groups())
        asm += [f"DEF PEON_ATLAS_{key}_WORLD_X EQU {x}", f"DEF PEON_ATLAS_{key}_WORLD_Y EQU {y}"]
        manifest["objectives"][key] = {"map": name, "xy": [x, y]}
    (ROOT / "gfx/pack/peon_atlas_geometry.asm").write_text("\n".join(asm) + "\n")
    binary = bytearray()
    public = Image.new("RGBA", (8, 8))
    native = Image.new("P", (8, 8))
    native.putpalette([255,255,255,170,170,170,85,85,85,0,0,0] + [0] * 756)
    for y, row in enumerate(AVATAR):
        values = list(map(int, row))
        binary += bytes([sum((v & 1) << (7 - x) for x, v in enumerate(values)),
                         sum((v >> 1) << (7 - x) for x, v in enumerate(values))])
        for x, value in enumerate(values):
            native.putpixel((x, y), value)
            if value:
                public.putpixel((x, y), (*(v << 3 for v in PALETTE[value]), 255))
    native.save(ROOT / "gfx/pack/peon_atlas_avatar.png")
    (ROOT / "gfx/pack/peon_atlas_avatar.2bpp").write_bytes(binary)
    public.save(OUT / "peon_atlas_avatar_8x8.png")
    public.resize((128, 128), Image.Resampling.NEAREST).save(OUT / "peon_atlas_avatar_16x.png")
    manifest["avatar"]["2bpp_sha256"] = hashlib.sha256(binary).hexdigest()
    manifest["limitations"] = ["Uses the current compact map geography; requested seven-screen Valley layout is not implemented.",
        "Linked room players are represented at their exact exterior return door, not their indoor walking coordinates.",
        "Cave coordinates project onto the cave page; an active medallion also marks its actual Valley entrance.",
        "8x8 markers may partially overlap at thumbnail scale; the green avatar has OAM priority."]
    (OUT / "geometry_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print("Seven current-map projections, truthful room doors and native green peon glyph generated.")


if __name__ == "__main__":
    main()
