#!/usr/bin/env python3
"""Reuse immutable v0.2.2 artwork without replaying native data generators."""
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'references/generated/durotar_v022'
OUT = ROOT / 'references/generated/durotar_v023'
CAPTURE_KINDS = {'capture', 'diagnostic', 'historical'}


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def snapshot():
    return {p.relative_to(SOURCE).as_posix(): digest(p)
            for p in SOURCE.rglob('*') if p.is_file()}


def main():
    before = snapshot()
    gallery = json.loads((SOURCE / 'gallery_manifest.json').read_text())
    image_kinds = {Path(image['path']).relative_to('durotar_v022').as_posix(): image['kind']
                   for image in gallery['images'] if image['path'].startswith('durotar_v022/')}
    copied, retained = [], []
    for path in sorted(SOURCE.rglob('*')):
        if not path.is_file():
            continue
        relative = path.relative_to(SOURCE)
        name = relative.as_posix()
        # A new release gets fresh runtime captures and reports from its ROM.
        if (any(part.endswith('_validation') or part in {'in_game', 'save_upgrade', '__pycache__'}
                for part in relative.parts)
                or any(word in path.name.lower() for word in ('unexpected', 'failure', 'debug', 'trace'))):
            continue
        if path.suffix.lower() in {'.png', '.gif'}:
            if relative.parts[0] in {'ambient_music', 'title_music', 'sound_effects'}:
                continue  # Audio screenshots/plots are generated by fresh APU tests.
            if name in image_kinds and image_kinds[name] in CAPTURE_KINDS:
                continue
            if name not in image_kinds and not path.name.startswith('concept_'):
                continue
        elif path.suffix == '.json':
            data = json.loads(path.read_text())
            if (not isinstance(data, dict) or 'rom_sha256' in data
                    or relative.parent == Path('.')
                    or path.name.startswith(('gallery_', 'validation'))):
                continue
        else:
            continue
        target = OUT / relative
        if target.exists():
            if digest(target) != before[name]:
                retained.append(name)  # A newer v023 export takes precedence.
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(path, target)
        copied.append(name)
    assert snapshot() == before, 'Published v0.2.2 files changed during asset staging'
    OUT.mkdir(parents=True, exist_ok=True)
    report = dict(source_directory=SOURCE.relative_to(ROOT).as_posix(),
                  output_directory=OUT.relative_to(ROOT).as_posix(),
                  source_files_verified_unchanged=len(before), copied_files=copied,
                  newer_v023_exports_preserved=retained,
                  native_data_generators_executed=False,
                  old_runtime_reports_or_captures_copied=False,
                  source_assets_retained=True)
    (OUT / 'retained_assets_manifest.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(dict(copied_files=len(copied), newer_exports_preserved=len(retained),
                          published_v022_files_unchanged=len(before))))


if __name__ == '__main__':
    main()
